# 安全检测系统配置文件
# 系统环境: development/production/testing
environment: development

# 系统密钥，生产环境请务必修改
secret_key: "your-secret-key-here-change-in-production"

# 数据保留天数
data_retention_days: 90

# 数据清理计划 (cron格式)
cleanup_schedule: "0 2 * * *"

# 数据库配置
database:
  url: "sqlite:///security_events.db"
  echo: false
  pool_size: 10
  max_overflow: 20

# Redis缓存配置
redis:
  url: "redis://localhost:6379/0"
  password: null
  max_connections: 50

# 大语言模型配置
llm:
  provider: "openai"
  api_key: ""  # 请填入您的OpenAI API密钥
  model: "gpt-3.5-turbo"
  daily_limit: 1000
  enable_cache: true
  cache_ttl: 3600

# 安全检测配置
detection:
  confidence_threshold: 0.8
  enable_sql_detection: true
  enable_xss_detection: true
  enable_cmd_detection: true
  max_request_size: 1048576  # 1MB

# API服务配置
api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  cors_origins:
    - "*"
  rate_limit: "100/minute"

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: null  # 不写入文件，只在控制台输出
  max_bytes: 10485760  # 10MB
  backup_count: 5 